apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
   containers:
      - image: kodekloud/examplevotingapp_result:v1
        name: result-app
        ports:
          - containerPort: 80

