apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
   containers:
      - image: kodekloud/examplevotingapp_vote:v1
        name: voting-app
        ports:
          - containerPort: 80

